version: 2.1

jobs:
  Build:  
    working_directory: ~/repo         
    docker:                            
      - image: circleci/node:14
    steps:                             
      - checkout                      
      - run: npm ci                 
      - run: CI=false npm run build    
      - persist_to_workspace:         
          root: ~/repo
          paths: ['.']
  Test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:              
          at: .
      - run: npm run test            
  Store_Artifacts:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: .
      - store_artifacts:             
          path: ./build
          destination: build/
  Deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: .
      - run:                          
          name: Deploy Main branch to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

# Invoke jobs via workflows
workflows:
  Build_Test_Deploy:    
    jobs:
    - Build
    - Test:
        requires:
          - Build
    - Store_Artifacts:
        requires:
          - Test
    - Depploy:
        requires:
          - Test
        filters:         
          branches:
            only:
              - main